version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - sphinx-apidoc -o docs/source/ src

conda:
  environment: environment.yaml

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
