name: FAME
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - bzip2
  - ca-certificates
  - expat
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libmpdec
  - libstdcxx-ng
  - libuuid
  - ncurses
  - openssl
  - pip
  - python
  - python_abi
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - jax
      - jax-cuda12-pjrt
      - jax-cuda12-plugin
      - jaxlib
      - ml-dtypes
      - numpy
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvcc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - opt-einsum
      - petsc
      - petsc4py
      - scipy
